# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\second_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import random

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QIntValidator

import third_window
from third_window import Ui_MainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, images_list):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1294, 963)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(550, 880, 211, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.reroll_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.reroll_button.setObjectName("reroll_button")
        self.horizontalLayout_5.addWidget(self.reroll_button)
        self.next_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.next_button.setObjectName("next_button")
        self.horizontalLayout_5.addWidget(self.next_button)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 1261, 821))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.img_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.img_1.setMaximumSize(QtCore.QSize(200, 200))
        self.img_1.setObjectName("img_1")
        self.verticalLayout_6.addWidget(self.img_1, 0, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.img_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.img_2.setMaximumSize(QtCore.QSize(200, 200))
        self.img_2.setObjectName("img_2")
        self.verticalLayout_6.addWidget(self.img_2, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_2.setMaximumSize(QtCore.QSize(50, 50))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.img_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.img_3.setMaximumSize(QtCore.QSize(200, 200))
        self.img_3.setObjectName("img_3")
        self.verticalLayout_6.addWidget(self.img_3, 0, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setMaximumSize(QtCore.QSize(50, 50))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_10.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.img_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.img_4.setMaximumSize(QtCore.QSize(200, 200))
        self.img_4.setObjectName("img_4")
        self.verticalLayout_4.addWidget(self.img_4, 0, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_4.setMaximumSize(QtCore.QSize(50, 50))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.img_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.img_5.setMaximumSize(QtCore.QSize(200, 200))
        self.img_5.setObjectName("img_5")
        self.verticalLayout_4.addWidget(self.img_5, 0, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_5.setMaximumSize(QtCore.QSize(50, 50))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.img_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.img_6.setMaximumSize(QtCore.QSize(200, 200))
        self.img_6.setObjectName("img_6")
        self.verticalLayout_4.addWidget(self.img_6, 0, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_6.setMaximumSize(QtCore.QSize(50, 50))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.img_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.img_7.setMaximumSize(QtCore.QSize(200, 200))
        self.img_7.setObjectName("img_7")
        self.verticalLayout_8.addWidget(self.img_7, 0, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_7.setMaximumSize(QtCore.QSize(50, 50))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.img_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.img_8.setMaximumSize(QtCore.QSize(200, 200))
        self.img_8.setObjectName("img_8")
        self.verticalLayout_8.addWidget(self.img_8, 0, QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_8.setMaximumSize(QtCore.QSize(50, 50))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.img_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.img_9.setMaximumSize(QtCore.QSize(200, 200))
        self.img_9.setObjectName("img_9")
        self.verticalLayout_8.addWidget(self.img_9, 0, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_9.setMaximumSize(QtCore.QSize(50, 50))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_10.addLayout(self.verticalLayout_8)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(600, 850, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1294, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.onlyInt = QIntValidator()
        self.lineEdit.setValidator(self.onlyInt)
        self.window = MainWindow
        self.noun_images = images_list
        self.next_button.setEnabled(False)
        self.img_1.setScaledContents(True)
        self.img_2.setScaledContents(True)
        self.img_3.setScaledContents(True)
        self.img_4.setScaledContents(True)
        self.img_5.setScaledContents(True)
        self.img_6.setScaledContents(True)
        self.img_7.setScaledContents(True)
        self.img_8.setScaledContents(True)
        self.img_9.setScaledContents(True)

        self.retranslateUi(MainWindow)

        self.reroll_imgages()

        self.next_button.clicked.connect(self.next_step)
        self.img_1.setTextInteractionFlags(Qt.TextSelectableByMouse)
        self.lineEdit.textChanged.connect(self.enableNext)
        self.reroll_button.clicked.connect(self.reroll_imgages)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def enableNext(self):
        if len(self.lineEdit.text()) > 0:
            self.next_button.setEnabled(True)
        else:
            self.next_button.setEnabled(False)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Content Images"))
        self.reroll_button.setText(_translate("MainWindow", "Reroll"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.img_1.setText(_translate("MainWindow", "One"))
        self.label.setText(_translate("MainWindow", "1"))
        self.img_2.setText(_translate("MainWindow", "Two"))
        self.label_2.setText(_translate("MainWindow", "2"))
        self.img_3.setText(_translate("MainWindow", "three"))
        self.label_3.setText(_translate("MainWindow", "3"))
        self.img_4.setText(_translate("MainWindow", "four"))
        self.label_4.setText(_translate("MainWindow", "4"))
        self.img_5.setText(_translate("MainWindow", "five"))
        self.label_5.setText(_translate("MainWindow", "5"))
        self.img_6.setText(_translate("MainWindow", "six"))
        self.label_6.setText(_translate("MainWindow", "6"))
        self.img_7.setText(_translate("MainWindow", "seven"))
        self.label_7.setText(_translate("MainWindow", "7"))
        self.img_8.setText(_translate("MainWindow", "eight"))
        self.label_8.setText(_translate("MainWindow", "8"))
        self.img_9.setText(_translate("MainWindow", "nine"))
        self.label_9.setText(_translate("MainWindow", "9"))

    def reroll_imgages(self):
        self.indexes = self.generate_random_indexes()

        pic_1 = QtGui.QPixmap(os.path.join(self.noun_images[self.indexes[0][0]][self.indexes[0][1]]))
        pic_1.scaled(200, 200, Qt.KeepAspectRatio)
        self.img_1.setPixmap(pic_1)
        pic_2 = QtGui.QPixmap(os.path.join(self.noun_images[self.indexes[1][0]][self.indexes[1][1]]))
        pic_2.scaled(200, 200, Qt.KeepAspectRatio)
        self.img_2.setPixmap(pic_2)
        pic_3 = QtGui.QPixmap(os.path.join(self.noun_images[self.indexes[2][0]][self.indexes[2][1]]))
        pic_3.scaled(200, 200, Qt.KeepAspectRatio)
        self.img_3.setPixmap(pic_3)
        pic_4 = QtGui.QPixmap(os.path.join(self.noun_images[self.indexes[3][0]][self.indexes[3][1]]))
        pic_4.scaled(200, 200, Qt.KeepAspectRatio)
        self.img_4.setPixmap(pic_4)
        pic_5 = QtGui.QPixmap(os.path.join(self.noun_images[self.indexes[4][0]][self.indexes[4][1]]))
        pic_5.scaled(200, 200, Qt.KeepAspectRatio)
        self.img_5.setPixmap(pic_5)
        pic_6 = QtGui.QPixmap(os.path.join(self.noun_images[self.indexes[5][0]][self.indexes[5][1]]))
        pic_6.scaled(200, 200, Qt.KeepAspectRatio)
        self.img_6.setPixmap(pic_6)
        pic_7 = QtGui.QPixmap(os.path.join(self.noun_images[self.indexes[6][0]][self.indexes[6][1]]))
        pic_7.scaled(200, 200, Qt.KeepAspectRatio)
        self.img_7.setPixmap(pic_7)
        pic_8 = QtGui.QPixmap(os.path.join(self.noun_images[self.indexes[7][0]][self.indexes[7][1]]))
        pic_8.scaled(200, 200, Qt.KeepAspectRatio)
        self.img_8.setPixmap(pic_8)
        pic_9 = QtGui.QPixmap(os.path.join(self.noun_images[self.indexes[8][0]][self.indexes[8][1]]))
        pic_9.scaled(200, 200, Qt.KeepAspectRatio)
        self.img_9.setPixmap(pic_9)

    def next_step(self):
        img_num = int(self.lineEdit.text())
        if 0 < img_num < 10:
            noun_image_path = self.noun_images[self.indexes[img_num-1][0]][self.indexes[img_num-1][1]]
            self.window.hide()
            self.main_window_3 = QtWidgets.QMainWindow()
            self.third_ui = third_window.Ui_MainWindow()
            self.third_ui.setupUi(self.main_window_3, noun_image_path)
            self.main_window_3.show()
        else:
            error_dialog = QtWidgets.QErrorMessage()
            error_dialog.showMessage('You have entered the wrong number!')
            error_dialog.exec_()

    def generate_random_indexes(self):
        index_list = []
        for i in range(9):
            x = 0
            y = 0
            while True:
                x = random.randint(0, len(self.noun_images) - 1)
                y = random.randint(0, len(self.noun_images[0]) - 1)
                if x and y not in index_list:
                    index_list.append([x, y])
                    break

        return index_list
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
